#!/bin/sh

# notify-send v5.5
# Bruno GNUser Dantas GPLv3

# user variables:
font="monospace:width=10" # desired font (use "monospace" or specify a fixed-width font)
char_px=10                # character width of the above font (in pixels)
desired_box_char=24       # desired box width (in characters)
x_pos=1020                # desired x coordinate of notification
y_pos=36                  # desired y coordinate of notification

main()
{
	parse_args "$@"
	create_notification
}

parse_args()
{
	[ $# -lt 2 ] && show_usage

	title="$1"
	message="$2"
	timeout=${3:-2} # use arg3 or default 2 secs
}

show_usage()
{
	echo "Usage: $(basename $0) <title> <message> [<timeout>]"
	echo "Example: $(basename $0) 'An important message' 'Keep it simple!' 5"
	exit
}

create_notification()
{
	(echo "$title"; echo ' '; echo "$message" | fold -s -w $desired_box_char) | 
	dzen2 -bg black -fg white -tw $box_px -w $box_px -fn "$font" -l 5 -e 'onstart=uncollapse' -x $x_pos -y $y_pos -p $timeout
	exit
}

# internal variables:
box_px=$(( char_px * desired_box_char )) # box width in pixels

main "$@"
